apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "slurm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "slurm.name" . }}
    spec:
      containers:
        - name: slurmctld
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/entrypoint.sh", "slurmctld"]
          volumeMounts:
            - name: slurm-config
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
              readOnly: true
            - name: munge-key
              mountPath: /etc/munge/munge.key
              subPath: munge.key
              readOnly: true
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
        - name: munge-key
          secret:
            secretName: slurm-munge-key
