apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm.fullname" . }}-ctld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "slurm.name" . }}
      role: controller
  template:
    metadata:
      labels:
        app: {{ include "slurm.name" . }}
        role: controller
    spec:
      hostname: slurmctld
      containers:
        - name: slurmctld
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/entrypoint.sh", "slurmctld"]
          volumeMounts:
            - name: slurm-config
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
              readOnly: true
            - name: munge-key
              mountPath: /etc/munge/munge.key
              subPath: munge.key
              readOnly: true
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
        - name: munge-key
          secret:
            secretName: slurm-munge-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "slurm.name" . }}
      role: compute
  template:
    metadata:
      labels:
        app: {{ include "slurm.name" . }}
        role: compute
    spec:
      hostname: c1
      containers:
        - name: slurmd
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/entrypoint.sh", "slurmd", "-N", "c1"]
          volumeMounts:
            - name: slurm-config
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
              readOnly: true
            - name: munge-key
              mountPath: /etc/munge/munge.key
              subPath: munge.key
              readOnly: true
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
        - name: munge-key
          secret:
            secretName: slurm-munge-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmdbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "slurm.name" . }}
      role: dbd
  template:
    metadata:
      labels:
        app: {{ include "slurm.name" . }}
        role: dbd
    spec:
      hostname: slurmdbd
      containers:
        - name: slurmdbd
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/entrypoint.sh", "slurmdbd", "-f", "/config/slurmdbd.conf"]
          volumeMounts:
            - name: slurmdbd-config
              mountPath: /config
              readOnly: true
            - name: munge-key
              mountPath: /etc/munge/munge.key
              subPath: munge.key
              readOnly: true
      volumes:
        - name: slurmdbd-config
          configMap:
            name: slurm-config
        - name: munge-key
          secret:
            secretName: slurm-munge-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10.11
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MARIADB_DATABASE
              value: slurm_acct_db
            - name: MARIADB_USER
              value: slurm
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: init-script
          configMap:
            name: mysql-init-script

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
stringData:
  root-password: rootpass
  user-password: slurmpass
