apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS slurm_acct_db;
    CREATE USER IF NOT EXISTS 'slurm'@'%' IDENTIFIED BY 'slurmpass';
    GRANT ALL PRIVILEGES ON slurm_acct_db.* TO 'slurm'@'%';
    FLUSH PRIVILEGES;
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    skip-name-resolve
    default_authentication_plugin=mysql_native_password

    [client]
    default-character-set=utf8mb4

    [mysql]
    default-character-set=utf8mb4