apiVersion: v1
kind: Service
metadata:
  name: c1
spec:
  selector:
    app: {{ include "slurm.name" . }}
    role: compute
  ports:
    - port: 6818
      targetPort: 6818
---
apiVersion: v1
kind: Service
metadata:
  name: slurmdbd
spec:
  selector:
    app: {{ include "slurm.name" . }}
    role: dbd
  ports:
    - port: 6819
      targetPort: 6819
