apiVersion: v1
kind: Service
metadata:
  name: slurmctld
spec:
  selector:
    app: {{ include "slurm.name" . }}
    role: controller
  ports:
    - port: 6817
      targetPort: 6817
---
apiVersion: v1
kind: Service
metadata:
  name: c1
spec:
  selector:
    app: {{ include "slurm.name" . }}
    role: compute
  ports:
    - port: 6818
      targetPort: 6818