apiVersion: v1
kind: ConfigMap
metadata:
  name: slurm-config
data:
  slurm.conf: |
    ClusterName=docker-cluster
    ControlMachine=slurmctld
    ProctrackType=proctrack/linuxproc

    SlurmUser=slurm
    SlurmdSpoolDir=/var/spool/slurmd
    SlurmctldLogFile=/var/log/slurm/slurmctld.log
    SlurmdLogFile=/var/log/slurm/slurmd.log
    StateSaveLocation=/var/spool/slurm/state

    AuthType=auth/munge
    CryptoType=crypto/munge

    SchedulerType=sched/backfill
    SelectType=select/cons_res
    SelectTypeParameters=CR_Core

    NodeName=c1 CPUs=2 State=UNKNOWN
    PartitionName=debug Nodes=c1 Default=YES MaxTime=INFINITE State=UP
